services:
  - type: web
    name: telegram-bot-api
    env: docker
    region: virginia
    plan: pro
    healthCheckPath: /
    healthCheckPort: 10000
    disk:
      name: telegram-bot-api-data
      mountPath: /app/data
      sizeGB: 2
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
