services:
  - type: web
    name: telegram-bot-api
    env: docker
    region: virginia
    plan: pro
    healthCheckPath: /
    healthCheckPort: 10000  # Specify the health check port explicitly
    port: 80  # Tell Render to route traffic to port 80 (nginx)
    disk:
      name: telegram-bot-api-data
      mountPath: /app/data
      sizeGB: 10
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
